[package]
name = "spenso"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Lucien Huber <cargo+mail@lucien.ch>"]
description = "A tensor (n-dim array) network, iterating, and contraction (using automatic abstract index matching) library."

[lib]
path = "src/spenso.rs"


[profile.bench]
lto = "fat"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
insta = { version = "1.38.0", features = ["yaml", "json", "ron", "toml"] }

[[bench]]
name = "gamma_net"
harness = false
required-features = ["shadowing"]

[[bench]]
name = "evaluate_net"
harness = false
required-features = ["shadowing"]


[[example]]
name = "evaluate_network"
required-features = ["shadowing"]


[dependencies]
ahash = { version = "0.8.11", features = ["serde"] }
ambassador = "0.3.6"
bitvec = { version = "1.0.1", features = ["serde"] }
derive_more = "0.99.17"
duplicate = "1.0.0"
enum-try-as-inner = "0.1.1"
gat-lending-iterator = "0.1.5"
indexmap = { version = "2.2.6", features = ["serde"] }
num = { version = "0.4.3", features = ["serde"] }
rand = "0.8.5"
rand_xoshiro = "0.6.0"
serde = "1.0.201"
serde_toml = "0.0.1"
slotmap = { version = "1.0.7", features = ["serde"] }
smartstring = { version = "1.0.1", features = ["serde"] }
symbolica = { version = "0.5.0", optional = true }
# symbolica = { path = "../gammaloop/python/gammaloop/dependencies/symbolica" }
thiserror = "1.0.60"


[features]
shadowing = ["dep:symbolica"]

# [patch.crates-io]
# symbolica = { git = "https://github.com/lcnbr/symbolica" }
