name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    environment: symbolica_keys
    runs-on: ubuntu-latest
    env:
          SYMBOLICA_LICENSE: ${{ secrets.SYMBOLICA_LICENSE }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run benchmarks
      run: cargo bench 
